# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and install dependencies with Poetry
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - curl -sSL https://install.python-poetry.org | python3 -
      - poetry config virtualenvs.create false
      - poetry install

# Installs Sphinx with pip
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
