input_variables:
  - initializer_dummy_tool
  - user_input_instructions
initial_messages:
  - role: assistant
    content: Hello, I am Automata, OpenAI's most skilled coding system. How may I assist you today?
  - role: user
    content: Please carry out the following instruction "{user_input_instructions}"
  - role: assistant
    content: Thoughts:\\nFirst, I will initialize myself. Then I will continue on to carefully consider the user task and carry out the necessary actions.\\nAction:\\nI will call `initializer` to initialize myself.'
    function_call:
      name: initializer
      arguments: {}
  - role: user
    content: Observation:\\nContinue...
