# .github/workflows/build-docs.yml
name: Build Documentation

on:
  push:
    branches:
      - main # or replace with your default branch
  pull_request:
    branches:
      - main # or replace with your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # or the version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r automata/docs/requirements.txt  # replace with your requirements file path

      - name: Build docs
        run: make -C automata/docs/ html # replace with your Sphinx docs directory
