# .github/workflows/build-docs.yml
name: Build Documentation

on:
  push:
    branches:
      - main # or replace with your default branch
  pull_request:
    branches:
      - main # or replace with your default branch

# Installs Sphinx with pip
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10 # or the version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.create false
          poetry install

      - name: Build docs
        run: make -C docs/ html
