name: publish
on:
  push:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push the Docker image
      run: |
           docker build . --tag ghcr.io/emrgnt-cmplxty/automata:latest
           docker push ghcr.io/emrgnt-cmplxty/automata:latest
