name: Nightly Evaluation

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          poetry run python -m pip install --upgrade pip
          poetry install
          poetry run python -m pip install -e .

      - name: Run evaluation tests
        run: poetry run pytest -m evaluation --junitxml=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.xml
