name: Run Regression Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "^3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          poetry install

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Run regression tests
        run: |
          pytest -m regression
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
